stages:
  - start
  - build

variables:
  STORY_IMAGE: infrastructure/keep-assistant
  DOCKER_REPO: docker.samokat.io
  GIT_SSH_COMMAND: ssh -oStrictHostKeyChecking=no
  FROM_DOCKER_REGISTRY: ${DOCKER_REPO}/global-external/docker.io 

include:
  - project: 'devops/cicd'
    file: 'start/start.yml'
  - project: 'devops/cicd'
    file: 'base/kaniko_build.yml'
  - project: 'devops/cicd'
    file: 'build/node/build.yml'
